import { LitElement, html, nothing } from "lit";
import { reportsApi, type MonthlyReport, type ReportMetric, type YearReportResponse } from "./api.js";
import { formatReportValue, localizedMonth, metricDetail, type ReportFormat } from "./report-format.js";

type View = "monthly" | "year";
type MetricChoice = { key: string; label: string; format: ReportFormat; get: (report: MonthlyReport) => ReportMetric | null };
const choices: MetricChoice[] = [
  { key: "weight", label: "Average weight", format: "weight", get: (r) => r.weight?.average ?? null },
  { key: "systolic", label: "Average systolic", format: "pressure", get: (r) => r.bloodPressure?.averageSystolic ?? null },
  { key: "diastolic", label: "Average diastolic", format: "pressure", get: (r) => r.bloodPressure?.averageDiastolic ?? null },
  { key: "pulse", label: "Average pulse", format: "pulse", get: (r) => r.bloodPressure?.averagePulse ?? null },
  { key: "sleep-total", label: "Average total sleep", format: "duration", get: (r) => r.sleep.averageTotalSleepMinutes },
  { key: "sleep-awake", label: "Average awake time", format: "duration", get: (r) => r.sleep.averageAwakeMinutes },
  { key: "sleep-light", label: "Average light sleep", format: "duration", get: (r) => r.sleep.averageLightMinutes },
  { key: "sleep-deep", label: "Average deep sleep", format: "duration", get: (r) => r.sleep.averageDeepMinutes },
  { key: "sleep-rem", label: "Average REM sleep", format: "duration", get: (r) => r.sleep.averageRemMinutes },
  { key: "sleep-score", label: "Average Sleep score", format: "score", get: (r) => r.sleep.averageSleepScore },
  { key: "pap-usage", label: "Average PAP usage", format: "duration", get: (r) => r.pap.averageUsageMinutes },
  { key: "pap-events", label: "Average PAP events/hour", format: "decimal", get: (r) => r.pap.averageEventsPerHour },
  { key: "pap-seal", label: "Average PAP mask seal score", format: "decimal", get: (r) => r.pap.averageMaskSealScore },
  { key: "pap-onoff", label: "Average PAP mask on/off count", format: "decimal", get: (r) => r.pap.averageMaskOnOffCount },
  { key: "pap-score", label: "Average PAP total score", format: "score", get: (r) => r.pap.averageTotalScore },
];
const latestRange = () => { const now = new Date(); const start = new Date(now.getFullYear(), now.getMonth() - 11, 1); return { from: `${start.getFullYear()}-${String(start.getMonth() + 1).padStart(2, "0")}`, to: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}` }; };
const hashParams = () => new URLSearchParams(window.location.hash.split("?")[1] ?? "");

export class ReportsPage extends LitElement {
  static properties = { view: {}, from: { state: true }, to: { state: true }, years: { state: true }, selectedMetric: { state: true }, months: { state: true }, comparison: { state: true }, loading: { state: true }, error: { state: true } };
  declare view: View; declare private from: string; declare private to: string; declare private years: string; declare private selectedMetric: string; declare private months: MonthlyReport[]; declare private comparison: YearReportResponse | null; declare private loading: boolean; declare private error: string | null;
  constructor() { super(); const range = latestRange(); this.view = "monthly"; this.from = range.from; this.to = range.to; this.years = String(new Date().getFullYear()); this.selectedMetric = "weight"; this.months = []; this.comparison = null; this.loading = false; this.error = null; }
  protected createRenderRoot() { return this; }
  connectedCallback() { super.connectedCallback(); window.addEventListener("hashchange", this.handleHashChange); this.readUrl(); void this.load(); }
  disconnectedCallback() { window.removeEventListener("hashchange", this.handleHashChange); super.disconnectedCallback(); }
  private handleHashChange = () => { this.readUrl(); void this.load(); };
  protected updated(changed: Map<PropertyKey, unknown>) { if (changed.has("view") && changed.get("view") !== undefined) { this.readUrl(); void this.load(); } }
  private readUrl() { const params = hashParams(); const range = latestRange(); if (this.view === "monthly") { this.from = params.get("from") ?? range.from; this.to = params.get("to") ?? range.to; } else { this.years = params.get("years") ?? String(new Date().getFullYear()); this.selectedMetric = params.get("metric") ?? "weight"; } }
  private async load() { this.loading = true; this.error = null; try { if (this.view === "monthly") this.months = (await reportsApi.monthly(this.from, this.to)).months; else { const parts = this.years.split(",").map((value) => value.trim()); if (parts.some((value) => !/^\d{4}$/.test(value))) throw new Error("Enter calendar years as four digits, separated by commas."); const years = [...new Set(parts.map(Number))]; if (!years.length || years.length > 4) throw new Error("Choose between one and four years."); this.comparison = await reportsApi.yearOverYear(years); } } catch (error) { this.error = error instanceof Error ? error.message : "Unable to load report."; } finally { this.loading = false; } }
  private apply(event: SubmitEvent) { event.preventDefault(); const next = this.view === "monthly" ? `#/reports/monthly?from=${this.from}&to=${this.to}` : `#/reports/year-comparison?years=${encodeURIComponent(this.years)}&metric=${this.selectedMetric}`; if (window.location.hash === next) void this.load(); else window.location.hash = next; }
  private metric(metric: ReportMetric, format: ReportFormat) { return html`<span class="report-value">${formatReportValue(metric.value, format)}</span><small class=${`source-badge source-${metric.source}`}>${metricDetail(metric)}</small>`; }
  private section(title: string, columns: Array<{ label: string; format: ReportFormat; get: (report: MonthlyReport) => ReportMetric | null }>) { return html`<section class="report-card"><div class="card-heading"><div><span class="eyebrow">Monthly report</span><h2>${title}</h2></div></div><div class="report-table"><div class="report-row report-head"><span>Month</span>${columns.map(({ label }) => html`<span>${label}</span>`)}</div>${this.months.map((report) => html`<div class="report-row" style=${`--report-columns:${columns.length + 1}`}><strong>${localizedMonth(report.month)}</strong>${columns.map((column) => { const value = column.get(report); return html`<div data-label=${column.label}>${value ? this.metric(value, column.format) : html`<span class="report-value">—</span><small class="source-badge source-none">No data</small>`}</div>`; })}</div>`)}</div></section>`; }
  private renderMonthly() {
    const sleep = choices.filter((item) => item.key.startsWith("sleep-")).map((item) => ({ label: item.label.replace("Average ", ""), format: item.format, get: item.get }));
    const pap = choices.filter((item) => item.key.startsWith("pap-")).map((item) => ({ label: item.label.replace("Average PAP ", ""), format: item.format, get: item.get }));
    return html`${this.section("Weight", [{ label: "Average", format: "weight", get: (r) => r.weight?.average ?? null }, { label: "Minimum", format: "weight", get: (r) => r.weight?.minimum ?? null }, { label: "Maximum", format: "weight", get: (r) => r.weight?.maximum ?? null }, { label: "First", format: "weight", get: (r) => r.weight?.first ?? null }, { label: "Last", format: "weight", get: (r) => r.weight?.last ?? null }])}${this.section("Blood pressure", [{ label: "Systolic", format: "pressure", get: (r) => r.bloodPressure?.averageSystolic ?? null }, { label: "Diastolic", format: "pressure", get: (r) => r.bloodPressure?.averageDiastolic ?? null }, { label: "Pulse", format: "pulse", get: (r) => r.bloodPressure?.averagePulse ?? null }])}${this.section("Sleep", sleep)}${this.section("PAP", pap)}`;
  }
  private renderComparison() { if (!this.comparison) return nothing; const choice = choices.find(({ key }) => key === this.selectedMetric) ?? choices[0]!; return html`<section class="report-card"><div class="card-heading"><div><span class="eyebrow">Year comparison</span><h2>${choice.label}</h2></div></div><div class="comparison-table"><div class="comparison-row comparison-head" style=${`--year-columns:${this.comparison.meta.years.length + 1}`}><span>Month</span>${this.comparison.meta.years.map((year) => html`<span>${year}</span>`)}</div>${Array.from({ length: 12 }, (_, index) => html`<div class="comparison-row" style=${`--year-columns:${this.comparison!.meta.years.length + 1}`}><strong>${new Intl.DateTimeFormat(undefined, { month: "long" }).format(new Date(2024, index, 1, 12))}</strong>${this.comparison!.series.map(({ year, months }) => { const value = choice.get(months[index]!); return html`<div data-year=${year}>${value ? this.metric(value, choice.format) : html`<span class="report-value">—</span><small class="source-badge source-none">No data</small>`}</div>`; })}</div>`)}</div></section>`; }
  render() { return html`<main><section class="page-heading"><div><span class="eyebrow">Reporting</span><h1>${this.view === "monthly" ? "Monthly overview" : "Year comparison"}</h1><p>Daily values are used when available. Monthly summaries fill metrics that have no daily values.</p></div><span class="section-index">06</span></section><section class="report-controls"><form @submit=${this.apply}>${this.view === "monthly" ? html`<label>From month<input type="month" required .value=${this.from} @input=${(e: InputEvent) => (this.from = (e.target as HTMLInputElement).value)} /></label><label>To month<input type="month" required .value=${this.to} @input=${(e: InputEvent) => (this.to = (e.target as HTMLInputElement).value)} /></label>` : html`<label>Years <span>1–4, comma-separated</span><input required placeholder="2024, 2025" .value=${this.years} @input=${(e: InputEvent) => (this.years = (e.target as HTMLInputElement).value)} /></label><label>Metric<select .value=${this.selectedMetric} @change=${(e: Event) => (this.selectedMetric = (e.target as HTMLSelectElement).value)}>${choices.map((item) => html`<option value=${item.key}>${item.label}</option>`)}</select></label>`}<button class="primary-button" ?disabled=${this.loading}>${this.loading ? "Loading…" : "Apply"}</button></form></section>${this.error ? html`<div class="error-banner" role="alert"><strong>Unable to load report.</strong><span>${this.error}</span></div>` : nothing}${this.loading ? html`<div class="state"><span class="spinner"></span>Loading report…</div>` : this.view === "monthly" ? this.renderMonthly() : this.renderComparison()}</main>`; }
}
customElements.define("reports-page", ReportsPage);
